# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0005_auto_20151025_1347'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partlist',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='inbox',
            name='flags',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'date'),
        ),
    ]
