# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-02 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0006_auto_20160424_0935'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='partlist',
            managers=[
            ],
        ),
    ]
