# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0011_auto_20171231_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='received_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='date requested', verbose_name=b'requested'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'date'),
        ),
    ]
