# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0012_auto_20180313_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pool_amount',
        ),
    ]
