# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 13:24
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def rebuild_watson(apps, schema_editor):
    call_command("buildwatson", verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0013_remove_userprofile_pool_amount'),
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rebuild_watson, rebuild_watson),
    ]
