# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0013_auto_20180508_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='authorizer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
