# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0014_auto_20180511_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='view_all_headers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='exclude_from_unified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liberation',
            name='errored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liberation',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ask_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prefer_html_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unified_has_new_messages',
            field=models.BooleanField(default=False),
        ),
    ]
