# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0015_auto_20180512_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ask_images',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='display_images',
        ),
    ]
