# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0018_auto_20180519_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='disabled',
            field=models.BooleanField(default=False, help_text='This Inbox will no longer receive emails.', verbose_name='Disable Inbox'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='exclude_from_unified',
            field=models.BooleanField(default=False, verbose_name='Exclude from Unified Inbox'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pin Inbox to top'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_images',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Always ask to display images'), (1, 'Always display images'), (2, 'Never display images')], default=0, verbose_name='Display options for HTML emails', help_text='Warning: Images in HTML emails can be used to track if you read an email!'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefer_html_email',
            field=models.BooleanField(default=True, verbose_name='Prefer HTML emails'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefered_domain',
            field=models.ForeignKey(blank=True, help_text='Prefer a particular domain when adding a new Inbox', null=True, on_delete=django.db.models.deletion.CASCADE, to='inboxen.Domain'),
        ),
    ]
