# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0019_auto_20180522_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_delete',
            field=models.BooleanField(default=False, help_text='Delete emails after 30 days. Emails that have been marked as important will not be deleted.', verbose_name='Auto-delete emails'),
        ),
    ]
