# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0019_auto_20180522_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quota_options',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Reject new emails'), (1, 'Delete old emails')], default=0, verbose_name='What happens once your email quota is reached?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quota_percent_usage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
