# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0020_userprofile_auto_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='created',
            field=models.DateTimeField(verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date'),
        ),
    ]
