# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0020_auto_20180531_1705'),
        ('inboxen', '0020_userprofile_auto_delete'),
    ]

    operations = [
    ]
