# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0021_auto_20180607_2003'),
        ('inboxen', '0021_merge_20180601_1941'),
    ]

    operations = [
    ]
