# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 16:06
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0023_auto_20180522_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='search_tsv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='search_tsv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
