# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 17:11
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0024_auto_20190225_1606'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_tsv'], name='inboxen_ema_search__5d822f_gin'),
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_tsv'], name='inboxen_inb_search__0bbb83_gin'),
        ),
    ]
