# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0025_auto_20190304_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='partlist',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='partlist',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
