# Generated by Django 2.2.1 on 2019-05-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0026_auto_20190501_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='size',
        ),
    ]
