# Generated by Django 2.2.11 on 2020-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0027_remove_body_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receiving_emails',
            field=models.BooleanField(default=True),
        ),
    ]
