# Generated by Django 3.2.3 on 2021-06-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0028_userprofile_receiving_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liberation',
        ),
    ]
