# Generated by Django 4.2.4 on 2023-09-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxen', '0029_alter_partlist_level_alter_partlist_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partlist',
            options={'ordering': ['lft']},
        ),
        migrations.RemoveField(
            model_name='partlist',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='partlist',
            name='lft',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
