# Generated by Django 2.2.16 on 2020-12-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('check', models.SmallIntegerField(choices=[(0, 'Salmon'), (1, 'Celery')])),
                ('good', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['check', 'when'], name='monitor_che_check_b11649_idx'),
        ),
    ]
