# Generated by Django 4.2.4 on 2023-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='CheckItem',
        ),
        migrations.RemoveIndex(
            model_name='checkitem',
            name='monitor_che_check_b11649_idx',
        ),
        migrations.RenameField(
            model_name='checkitem',
            old_name='check',
            new_name='check_type',
        ),
        migrations.AddIndex(
            model_name='checkitem',
            index=models.Index(fields=['check_type', 'when'], name='monitor_che_check_t_51debb_idx'),
        ),
    ]
