# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 23:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_peoplepage_personinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
