# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('help', '0004_personinfo_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('app', models.CharField(choices=[(b'Tickets', b'tickets')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
