# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_apppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppage',
            name='app',
            field=models.CharField(choices=[(b'Tickets', b'tickets.urls')], max_length=255),
        ),
    ]
