# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_auto_20161029_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppage',
            name='app',
            field=models.CharField(choices=[(b'tickets.urls', b'Tickets')], max_length=255, unique=True),
        ),
    ]
