# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 14:52
from __future__ import unicode_literals

import inboxen.cms.fields
from django.db import migrations
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20171231_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=inboxen.cms.fields.RichTextField(allow_tags=[b'p', b'a', b'i', b'b', b'em', b'strong', b'ol', b'ul', b'li', b'pre', b'code', b'h1', b'h2', b'h3', b'h4', b'h5'], safe_attrs=[b'href', b'id'], validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
