# Generated by Django 4.2.4 on 2023-09-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20210913_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpbasepage',
            name='level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='lft',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.helpbasepage'),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='rght',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
