# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170215_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpindex',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
