# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170218_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='image',
            field=models.ForeignKey(blank=True, help_text=b"Images will be in the collection 'Profile Pictures'. Images will be displayed at 300x400", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
