# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 21:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170226_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='intro_paragraph',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'Text at the top of the page'),
        ),
    ]
