# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_setup_helpsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpbasepage',
            name='url_cache',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
