# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_helpbasepage_url_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpbasepage',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='helpbasepage',
            unique_together=set([('slug', 'parent')]),
        ),
    ]
