# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:18
from __future__ import unicode_literals

import cms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170917_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=cms.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='collection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='intro_paragraph',
            field=cms.fields.RichTextField(blank=True, help_text=b'Text at the top of the page'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='body',
            field=cms.fields.RichTextField(),
        ),
    ]
