# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 15:59
from __future__ import unicode_literals

import cms.fields
from django.db import migrations, models
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20170925_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpbasepage',
            name='description',
            field=models.TextField(blank=True, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='slug',
            field=models.SlugField(max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='title',
            field=models.CharField(max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='helpbasepage',
            name='url_cache',
            field=models.CharField(default=b'', max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='helppage',
            name='body',
            field=cms.fields.RichTextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='image',
            name='collection',
            field=models.CharField(max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='intro_paragraph',
            field=cms.fields.RichTextField(blank=True, help_text=b'Text at the top of the page', validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='body',
            field=cms.fields.RichTextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='name',
            field=models.CharField(max_length=255, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
