# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 17:29
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_tsv', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('field1', models.TextField()),
                ('field2', models.TextField()),
            ],
        ),
    ]
