# Generated by Django 2.2.6 on 2019-10-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchtestmodel'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS watson_searchentry",
            elidable=True,
        )
    ]
