# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=512, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='response',
            name='body',
            field=models.TextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
