# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161108_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=64, populate_from='subject', validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(max_length=512, validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
