# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180313_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='posted'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=64, populate_from='subject', validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
