# Generated by Django 3.2.11 on 2022-01-22 03:15

from django.db import migrations
import inboxen.cms.fields
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180607_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=inboxen.cms.fields.RichTextField(validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
