# Generated by Django 4.2.4 on 2023-09-15 22:20

from django.db import migrations
import inboxen.cms.fields
import inboxen.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=inboxen.cms.fields.RichTextField(allow_tags=['p', 'a', 'i', 'b', 'em', 'strong', 'ol', 'ul', 'li', 'pre', 'code', 'img'], safe_attrs=['href', 'src', 'alt'], validators=[inboxen.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
